- name: Commit and push changes
      run: |
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git add dist
            git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub Snake graph"
            git push || echo "No changes to push"
      env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
